image: ruby:2.7.4
services:
  - postgres:9.5
variables:
  POSTGRES_DB: jobvacancy_test
  POSTGRES_USER: jobvacancy
  POSTGRES_PASSWORD: jobvacancy
  DB_HOST: postgres
  TEST_DB_URL: postgres://jobvacancy:jobvacancy@postgres/jobvacancy_test
stages:
  - build
  - deploy_staging
  - deploy_master

job_build:
  stage: build
  script:
    - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
    - ruby -v
    - which ruby
    - gem install bundler -v 2.1.4 --no-document
    - bundle install --without staging production
    - RACK_ENV=test bundle exec rake

job_deploy_staging:
  stage: deploy_staging
  script:
  - gem install dpl
  - dpl --provider=heroku --app=jobvacancystagingmoscu --api-key=dd88d23d-eb36-4d89-9b7e-10818a9a89b3
  only:
  - staging

job_deploy_master:
  stage: deploy_master
  script:
  - gem install dpl
  - dpl --provider=heroku --app=jobvacancyprodmoscu --api-key=f88c1673-0c72-4cdb-869f-dcf2871a7ea5
  only:
  - master