version: "3.3"
services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    
  webapp:
    image: nicopaez/jobvacancy-dev:2.5.7
    command: "/bin/bash"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
        - .:/jobvacancy
    environment:
        RACK_ENV: "development"
        DATABASE_URL: "postgres://postgres:example@db:5432/postgres"
    depends_on:
      - db
    links:
      - db

